name: "tauri-build"
on:
  push:
    branches: [main]
    paths-ignore:
      - "*.md"
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    defaults:
      run:
        working-directory: app
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]
        platform: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ env.GITHUB_TOKEN }}
      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
          npm install -g typescript 
          yarn
      - name: install dependencies (macos only)
        run: |
          brew install gtk+3
          brew install webkitgtk
          npm install -g typescript 
          yarn
      - name: install dependencies (windows only)
        if: matrix.platform == 'windows-latest'
        run: |
          npm install -g typescript
          yarn
      - name: Build
        uses: tauri-apps/tauri-action@v0
        with:
          tagName: esp32datalogger-v__VERSION__
          releaseName: "Esp32 Data Logger v__VERSION__" # name of the release
          releaseBody: "Initial app public build. There may be bugs, please report them." # message to include in the release
          releaseDraft: false # set to false to publish the release as a finished product
          prerelease: false # set to true to mark the release as a pre-release
